### ISSUE TITLE
Emacs lisp implementation

### ISSUE THREAD

**Issue by sshbio** [asciimoo/drawille#25]
Hi!

I made an Elisp implementation.  It is based on matrix:  It convert a 2d vector to a drawille "image".

Here it is:
https://github.com/sshbio/elisp-drawille

It is very basic, but can also convert a string.

I enjoyed using drawille, and enjoyed writing this as well, so thank you!

**Comment by asciimoo** [comment]
@sshbio very nice! could you please add it to https://github.com/asciimoo/drawille#other-implementations--similar-projects?

**Comment by sshbio** [comment]
Yes!  I am forking right now..

**Comment by asciimoo** [comment]
Thanks! =)
