### ISSUE TITLE
Why does drawille does not draw in full terminal ?

### ISSUE THREAD

**Issue by darxtrix** [asciimoo/drawille#33]
My terminal size is 202*62 but drawille is drawing a line in half of the terminal, why so ?

```python
>>> import drawille
>>> drawille.getTerminalSize()
(202, 62)
>>> c = drawille.Canvas()
>>> for i in range(0,202):
... 	c.set(i,0)
... 
>>> print c.frame(0,0,202,62)
```

<img width="1426" alt="screen shot 2017-07-16 at 3 19 19 pm" src="https://user-images.githubusercontent.com/5263761/28246550-29a40acc-6a3a-11e7-9bef-314e23ee7e3b.png">

**Comment by asciimoo** [comment]
@darxtrix `getTerminalSize()` measures the terminal size in characters, but drawille has 4x2 pixel for each character. That's why the line's width in the screenshot is exactly the half of your terminal's width.
Multiply the width by 2 and the height by 4 and it will produce the desired output.

**Comment by darxtrix** [comment]
Thanks a ton, I did a bit digging into code and find the same workaround.
