### ISSUE TITLE
Compatible fonts?

### ISSUE THREAD

**Issue by dominikheinz** [asciimoo/drawille#46]
Hey,
So, I tried installing a bunch of fonts (including the ones you listed, such as Terminus), but I still have problems rendering the braille characters.

Can you link a font that will work for sure?
Or provide a way to patch in braille support in an existing font. There is https://aur.archlinux.org/packages/ttf-ubraille/ and I wonder if it can patched in with NerdFonts or something like this. I tried doing it myself, but without success.

A more concise explanation on how the fonts on the system must be configured to use this would be appreciated!

**Comment by asciimoo** [comment]
What is the problem exactly? Can your terminal handle unicode characters? It works well for me with terminus and fixed fonts using rxvt-unicode terminal

**Comment by dominikheinz** [comment]
The other fonts I had either didn't have braille characters at all, or they rendered them ugly (e.g. also showing the empty cells of a braille character, instead of only the actual dots).

I am now using DejaVuSansMono, which works absolutely perfectly. You might want to add this one to the README of suggested fonts.
